name: CI
on:
  push:
    branches:
      - "**"
env:
  PNPM_VERSION: 10.7.1
  NODE_VERSION: 22.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: "${{ env.PNPM_VERSION }}"
      - uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "pnpm"
          
      - run: pnpm install --frozen-lockfile
      - run: pnpm run all
